version: "3.5"

services:
  frontend:
    image: my-registry:55000/rest-front:ci-${BUILD_NUMBER}
    ports:
      - 80
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.restaurants.rule=Host(`restaurants.aleksvagapitov.com`)' # Put in your domain
        - 'traefik.http.routers.restaurants.entrypoints=websecure'
        - 'traefik.http.routers.restaurants.tls.certresolver=letsencrypt'
        - 'traefik.http.routers.restaurants.service=restaurantsservice'
        - 'traefik.http.services.restaurantsservice.loadbalancer.server.port=80' # Required in swarms, https://doc.traefik.io/traefik/v2.0/routing/providers/docker/#services
    network:
      - infrastructure

  backend:
    image: my-registry:55000/rest-back:ci-${BUILD_NUMBER}
    depends_on:
      - "restaurants-db"
      - "mailhog"
      - "minio"
    environment:
      ConnectionStrings__DatabaseConnection: "Host=restaurants-db;Port=5432;Username=user;Password=password123;Database=Restaurants;"
      EmailSettings__MailServer: "mailhog"
      EmailSettings__MailPort: 1025
      Minio__Endpoint: "minio:9000"
      Minio__ApiSecret: "minioadmin"
      Minio__ApiKey: "minioadmin"
      Minio__BucketName: "restaurants"
      Minio__AccessPoint: "minio:9000"
      LocationApiParameters__ApiKey: ""
      TokenKey: "super secret key"
    ports:
      - 80
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.restaurantsback.rule=Host(`restaurantsback.aleksvagapitov.com`)' # Put in your domain
        - 'traefik.http.routers.restaurantsback.entrypoints=websecure'
        - 'traefik.http.routers.restaurantsback.tls.certresolver=letsencrypt'
        - 'traefik.http.routers.restaurantsback.service=restaurantsbackservice'
        - 'traefik.http.services.restaurantsbackservice.loadbalancer.server.port=80' # Required in swarms, https://doc.traefik.io/traefik/v2.0/routing/providers/docker/#services
    links:
      - "restaurants-db:restaurants-db"
      - "mailhog:mailhog"
      - "minio:minio"
    network:
      - infrastructure

  restaurants-db:
    image: postgis/postgis:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: Restaurants
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: 'server /export'

networks:
  infrastructure:
    external: true
